---
title: "Project 2 Cloud Data Code Appendix"
author: "Yicheng Shen (Student ID: 2806571) & Yunhong Bao (Student ID: 2427527)"
date: "December 6, 2022"
header-includes: 
      - \usepackage{amsmath}
output: 
    pdf_document    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = F, cache = TRUE, warning = F, message = F)
library(mosaic)
library(GGally)
library(caret)
library(ggfortify)
library(gridExtra)
library(MASS)
library(e1071)
library(class)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


## EDA 

*scale in regression*

```{r read data and give name}
image_1 <- read.table("image_data/imagem1.txt")
image_2 <- read.table("image_data/imagem2.txt")
image_3 <- read.table("image_data/imagem3.txt")
var_name <- c("Y_coord", "X_coord", "Cloud", "NDAI", "SD", "CORR", "DF","CF","BF","AF","AN")
colnames(image_1) = colnames(image_2) = colnames(image_3) <- var_name
image_1$Cloud <- factor(image_1$Cloud)
image_2$Cloud <- factor(image_2$Cloud)
image_3$Cloud <- factor(image_3$Cloud)
```

```{r summary and dim}
summary(image_1)
summary(image_2)
summary(image_3)
dim(image_1)
dim(image_2)
dim(image_3)
```

```{r check na}
any(apply(image_1, 2, is.na))
any(apply(image_2, 2, is.na))
any(apply(image_3, 2, is.na))
```



```{r feature boxplot}
# image_1 %>% 
# ggplot() + geom_boxplot(aes(x=Cloud, y=SD)) 

all_image <- rbind(image_1 %>% mutate(image = "1"), image_2 %>% mutate(image = "2"), image_3 %>% mutate(image = "3"))
 
all_image%>% 
  ggplot() + geom_boxplot(aes(x=Cloud, y=NDAI, color = image)) 

all_image %>% 
  ggplot() + geom_boxplot(aes(x=Cloud, y=SD, color = image)) 

all_image %>% 
  ggplot() + geom_boxplot(aes(x=Cloud, y=CORR, color = image)) 
```


```{r pairwise, message = F, warning = F}
image_1 %>%
  dplyr::select(Cloud, NDAI, SD, CORR) %>% ggpairs()

image_2 %>%
  dplyr::select(Cloud, NDAI, SD, CORR) %>% ggpairs()

image_3 %>%
  dplyr::select(Cloud, NDAI, SD, CORR) %>% ggpairs()
```


*Do a PCA on the angle *
```{r angle corr}
image_1 %>% dplyr::select(DF:AN) %>% 
  ggpairs()
image_2 %>% dplyr::select(DF:AN) %>% 
  ggpairs()
image_3 %>% dplyr::select(DF:AN) %>% 
  ggpairs()
```


```{r cloud map}
# library(sf)
# ggplot(data = world) +
#     geom_sf() +
#     geom_point(data = image_1, aes(x = X-coord, y = Y-coord), size = 4, 
#         shape = 23, fill = "darkred") +
#     coord_sf(xlim = c(-88, -78), ylim = c(0, 33), expand = FALSE)

Palette_1 <- c("gray","black", "white")

map_1 <- image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size = 0.5) +
  theme_map() + theme(legend.position = "none") +
  labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_1)

map_2 <- image_2 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size =  0.5) +
  theme_map() + theme(legend.position = "none") +
  labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_1) 

map_3 <- image_3 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size = 0.5) +
  theme_map() + theme(legend.position = "none") +
  labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_1)
# map_1
# map_2
# map_3
```

```{r arranged map, fig.width=12,fig.height=4}
grid.arrange(arrangeGrob(map_1 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         map_2 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         map_3 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         nrow = 1))
```


*Better map?*

```{r new map}
Palette_2 <- c("gray", "white")

map1 <- image_1 %>%
  filter(Cloud != 0) %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size = 0.5) +
  theme_dark() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_2)

map2 <- image_2 %>%
  filter(Cloud != 0) %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size = 0.5) +
  theme_dark() + labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_2)

map3 <- image_3 %>%
  filter(Cloud != 0) %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Cloud), size = 0.5) +
  theme_dark() + labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") +
  scale_colour_manual(values = Palette_2)
# map1
# map2
# map3
```

```{r arrange map, fig.width=12,fig.height=4}
map_legend <- lemon::g_legend(map1 +  guides(colour = guide_legend(nrow = 1)))

grid.arrange(arrangeGrob(map1 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         map2 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         map3 + ggeasy::easy_center_title() + theme(legend.position="none"),
                         nrow = 1),
             map_legend, nrow = 2, heights = c(10, 1))
```


```{r image 1 covariate map, fig.width=12,fig.height=3.5}
NDAI_plot <- image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = NDAI), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate")

SD_plot <- image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = SD), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate")

CORR_plot <- image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = CORR), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 


grid.arrange(NDAI_plot + ggeasy::easy_center_title(),
             SD_plot + ggeasy::easy_center_title(),
             CORR_plot + ggeasy::easy_center_title(),
             nrow = 1)
```


```{r image 2 covariate map, fig.width=12,fig.height=3.5}
NDAI_plot <- image_2 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = NDAI), size = 0.5) +
  theme_map() + labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") 

SD_plot <- image_2 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = SD), size = 0.5) +
  theme_map() + labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") 

CORR_plot <- image_2 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = CORR), size = 0.5) +
  theme_map() + labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") 

grid.arrange(NDAI_plot + ggeasy::easy_center_title(),
             SD_plot + ggeasy::easy_center_title(),
             CORR_plot + ggeasy::easy_center_title(),
             nrow = 1)
```


```{r image 3 covariate map, fig.width=12,fig.height=3.5}
NDAI_plot <- image_3 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = NDAI), size = 0.5) +
  theme_map() + labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") + 
  scale_color_gradient(low="black", high="white")

SD_plot <- image_3 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = SD), size = 0.5) +
  theme_map() + labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") + 
  scale_color_gradient(low="black", high="white")

CORR_plot <- image_3 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = CORR), size = 0.5) +
  theme_map() + labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") + 
  scale_color_gradient(low="black", high="white")

grid.arrange(NDAI_plot + ggeasy::easy_center_title(),
             SD_plot + ggeasy::easy_center_title(),
             CORR_plot + ggeasy::easy_center_title(),
             nrow = 1)
```


```{r angle map}
image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = DF), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 

image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = CF), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 

image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = BF), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 

image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = AF), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 

image_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = AN), size = 0.5) +
  theme_map() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 
```

# Remove cloud = 0 from here.

```{r filter zero, eval = T, echo = T}
Image_1 <- image_1 %>% filter(Cloud != "0") 
Image_2 <- image_2 %>% filter(Cloud != "0") 
Image_3 <- image_3 %>% filter(Cloud != "0") 
```


```{r hist covariate, fig.width=12, fig.height=3}
hist_1 <- Image_1 %>% 
  ggplot(aes(x = NDAI)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_2 <- Image_2 %>% 
  ggplot(aes(x = NDAI)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_3 <- Image_3 %>% 
  ggplot(aes(x = NDAI)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

grid.arrange(hist_1 + ggeasy::easy_center_title(),
             hist_2 + ggeasy::easy_center_title(),
             hist_3 + ggeasy::easy_center_title(),
             nrow = 1)

# +
#   scale_fill_manual(values = c("steelblue1", "hotpink1")) +
#   scale_color_manual(values = c("steelblue1", "hotpink1")) +
#   theme_bw()

hist_1 <- Image_1 %>% 
  ggplot(aes(x = SD)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_2 <- Image_2 %>% 
  ggplot(aes(x = SD)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_3 <- Image_3 %>% 
  ggplot(aes(x = SD)) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

grid.arrange(hist_1 + ggeasy::easy_center_title(),
             hist_2 + ggeasy::easy_center_title(),
             hist_3 + ggeasy::easy_center_title(),
             nrow = 1)


hist_1 <- Image_1 %>% 
  ggplot(aes(x = log(SD))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_2 <- Image_2 %>% 
  ggplot(aes(x = log(SD))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_3 <- Image_3 %>% 
  ggplot(aes(x = log(SD))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

grid.arrange(hist_1 + ggeasy::easy_center_title(),
             hist_2 + ggeasy::easy_center_title(),
             hist_3 + ggeasy::easy_center_title(),
             nrow = 1)



hist_1 <- Image_1 %>% 
  ggplot(aes(x = CORR )) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_2 <- Image_2 %>% 
  ggplot(aes(x = CORR )) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_3 <- Image_3 %>% 
  ggplot(aes(x = CORR )) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

grid.arrange(hist_1 + ggeasy::easy_center_title(),
             hist_2 + ggeasy::easy_center_title(),
             hist_3 + ggeasy::easy_center_title(),
             nrow = 1)
```



```{r angle hist, fig.width=12, fig.height=3.5}
hist_1 <- Image_1 %>% 
  ggplot(aes(x = (AF))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_2 <- Image_2 %>% 
  ggplot(aes(x = (AF))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

hist_3 <- Image_3 %>% 
  ggplot(aes(x = (AF))) +
  geom_density(aes(fill = Cloud, color = Cloud), alpha = 0.7) 

grid.arrange(hist_1 + ggeasy::easy_center_title(),
             hist_2 + ggeasy::easy_center_title(),
             hist_3 + ggeasy::easy_center_title(),
             nrow = 1)
```



# 2.Data Preparation 


# 2.a


#### Make a table of availble data: 
image 1 
115110 total
82148 Without 0 
16430 Test
65718 Train
52574 train
13144 val


```{r index groups, eval = F, echo = F}
# set.seed(8848)
# sample_index_1 <- sample(nrow(Image_1), nrow(Image_1)*0.8)
# Image_1_Train <- Image_1[sample_index_1,]
# train_index_1 <- sample(nrow(Image_1_Train), nrow(Image_1_Train)*0.8)
# Image_1_val <- Image_1_Train[-train_index_1,]
# Image_1_train <- Image_1_Train[train_index_1,]
# Image_1_Test <- Image_1[-sample_index_1,]
# 
# 
# sample_index_2 <- sample(nrow(Image_2), nrow(Image_2)*0.8)
# Image_2_Train <- Image_2[sample_index_2,]
# train_index_2 <- sample(nrow(Image_2_Train), nrow(Image_2_Train)*0.8)
# Image_2_val <- Image_2_Train[-train_index_2,]
# Image_2_train <- Image_2_Train[train_index_2,]
# Image_2_Test <- Image_2[-sample_index_2,]
# 
# 
# sample_index_3 <- sample(nrow(Image_3), nrow(Image_3)*0.8)
# Image_3_Train <- Image_3[sample_index_3,]
# train_index_3 <- sample(nrow(Image_3_Train), nrow(Image_3_Train)*0.8)
# Image_3_val <- Image_3_Train[-train_index_3,]
# Image_3_train <- Image_3_Train[train_index_3,]
# Image_3_Test <- Image_3[-sample_index_3,]
```


```{r 5 groups, fig.width=10, fig.height=4}
# summary(Image_1_train[,1:2])
# quantile(Image_1_train$X_coord, c(0.5))
# quantile(Image_1_train$Y_coord, c(0.2, 0.4, 0.6, 0.8))

seperate_fold <- function(train_data) {
  
  fold_1 <- train_data %>% filter( Y_coord  < 383*0.2 )
  fold_2 <- train_data %>% filter( 383*0.2 <= Y_coord, Y_coord  < 383*0.4 )
  fold_3 <- train_data %>% filter( 383*0.4 <= Y_coord, Y_coord  < 383*0.6 )
  fold_4 <- train_data %>% filter( 383*0.6 <= Y_coord, Y_coord  < 383*0.8 )
  fold_5 <- train_data %>% filter( 383*0.8 <= Y_coord )
  
return( rbind(fold_1 %>% mutate(Type = "Test"),
      fold_2 %>% mutate(Type = "Validation"),
      fold_3 %>% mutate(Type = "Train"),
      fold_4 %>% mutate(Type = "Train"),
      fold_5 %>% mutate(Type = "Train") ) ) 
}

Cut_1 <- seperate_fold(Image_1)
Cut_2 <- seperate_fold(Image_2)
Cut_3 <- seperate_fold(Image_3)


Cut_1_Map <- Cut_1 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  # geom_hline(yintercept = 383*0.2 ) + 
  # geom_hline(yintercept = 383*0.4) + 
  labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 

Cut_2_Map <- Cut_2 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  # geom_hline(yintercept = 383*0.2) + 
  # geom_hline(yintercept = 383*0.4) + 
  labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate")

Cut_3_Map <- Cut_3 %>%
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  # geom_hline(yintercept = 383*0.2 ) + 
  # geom_hline(yintercept = 383*0.4) + 
  labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") + theme(legend.position="none")


grid.arrange(arrangeGrob(Cut_1_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         Cut_2_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         Cut_3_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         nrow = 1),
             lemon::g_legend(Cut_1_Map +  guides(colour = guide_legend(nrow = 1))), nrow = 2, heights = c(10, 1))

Image_all_Cut <- rbind(Cut_1, Cut_2, Cut_3)

# dim(Image_all_CV)

prop.table(table(Image_all_Cut$Type))

Image_all_Cut %>% 
  group_by(Type) %>% 
  summarise(`Perct Cloud` = mean(Cloud == "1"))
```


```{r 5 KNN groups, fig.width=10, fig.height=4}
set.seed(8848)

KM_1 <- kmeans(Image_1[,1:2], centers = 5, nstart = 25)
KM_2 <- kmeans(Image_2[,1:2], centers = 5, nstart = 25)
KM_3 <- kmeans(Image_3[,1:2], centers = 5, nstart = 25)

Image_all_KM <- rbind(Image_1 %>% mutate(image = "1", cluster = KM_1$cluster),
                      Image_2 %>% mutate(image = "2", cluster = KM_2$cluster),
                      Image_3 %>% mutate(image = "3", cluster = KM_3$cluster))

Image_all_KM <- Image_all_KM %>% 
  mutate(Type = ifelse(cluster == "5", "Test", "Train"))  %>% 
  mutate(Type = ifelse(cluster == "4", "Validation", Type)) 

KM_1_Map <- Image_all_KM %>% filter(image == "1") %>% 
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  theme_bw() + labs(title = "Image 1", x = "X Coordinate", y = "Y Coordinate") 
# +  scale_color_manual(values = c("red", "blue", "green", "green", "green"))  

KM_2_Map <- Image_all_KM %>% filter(image == "2") %>% 
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  theme_bw() + labs(title = "Image 2", x = "X Coordinate", y = "Y Coordinate") 

KM_3_Map <-Image_all_KM %>% filter(image == "3") %>% 
  ggplot() + geom_point(aes(x = X_coord, y = Y_coord, color = Type), size = 0.5) +
  theme_bw() + labs(title = "Image 3", x = "X Coordinate", y = "Y Coordinate") 

grid.arrange(arrangeGrob(KM_1_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         KM_2_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         KM_3_Map + ggeasy::easy_center_title() + theme(legend.position="none"),
                         nrow = 1),
             lemon::g_legend(KM_1_Map +  guides(colour = guide_legend(nrow = 1))), nrow = 2, heights = c(10, 1))


Image_all_KM %>% 
  group_by(Type) %>% 
  summarise(`Perct Cloud` = mean(Cloud == "1"))
```

# 2.b

```{r accuaracy of trival predictor}
Image_all_Cut %>% 
  filter(Type == "Validation")%>% 
  mutate(Predict = "-1") %>% 
  summarise(Accuracy = mean(Predict == Cloud))

Image_all_Cut %>% 
  filter(Type == "Test")%>% 
  mutate(Predict = "-1") %>% 
  summarise(Accuracy = mean(Predict == Cloud))


Image_all_KM %>% 
  filter(Type == "Validation")%>% 
  mutate(Predict = "-1") %>% 
  summarise(Accuracy = mean(Predict == Cloud))

Image_all_KM %>% 
  filter(Type == "Test")%>% 
  mutate(Predict = "-1") %>% 
  summarise(Accuracy = mean(Predict == Cloud))
```


# 2.c

```{r}
pca_result <- prcomp(Image_all_Cut %>% dplyr::select(NDAI:AN), cetner = T, scale. = T) 
as.matrix(pca_result$rotation )

cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$NDAI)
cor( as.numeric(Image_all_Cut$Cloud), log(Image_all_Cut$SD))
cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$CORR)

cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$DF)
cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$CF)
cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$BF)
cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$AF)
cor( as.numeric(Image_all_Cut$Cloud), Image_all_Cut$AN)
```


**For now, choose the first three features.**

# 2d CV Master

write some shit



# 3. Model Fitting & Validation

# 3.a


```{r train and test}
Image_Train_Cut <- Image_all_Cut %>%  filter(Type != "Test")
Image_Test_Cut <- Image_all_Cut %>%  filter(Type == "Test")
Image_Train_KM <- Image_all_KM %>%  filter(Type != "Test")
Image_Test_KM <- Image_all_KM %>%  filter(Type == "Test")
```


```{r}
CV_Master <-
  function(classifier, train_coord, train_feature, train_label, K, loss_fun) {
    # if classifer not in given choice
    
    fold_index = kmeans(train_coord, centers = K, nstart = 25)
    dat = cbind(train_feature, train_label)
    dat$fold_index = fold_index$cluster
    
    if (classifier == "Logistic")
    {
      glm_result <- list()
      prediction <- list()
      for (i in 1:K) {
        dat_CV_train = dat %>% filter(fold_index != i)
        dat_CV_test = dat %>% filter(fold_index == i)
        glm_result[[i]] = glm(paste("train_label ~ ", paste(names(
          train_feature
        ), collapse = "+"), sep = ""),
        data = dat_CV_train,
        family = 'binomial')
        prob = predict(glm_result[[i]], dat_CV_test, type = "response")
        prediction[[i]] = ifelse(prob > 0.5, 1,-1)
      }
      
    }
    
    if (classifier == "LDA")
    {
      LDA_model <- list()
      prediction <- list()
      for (i in 1:K) {
        dat_CV_train = dat %>% filter(fold_index != i)
        dat_CV_test = dat %>% filter(fold_index == i)
        LDA_model[[i]] = lda(paste("train_label ~ ", paste(names(
          train_feature
        ), collapse = "+"), sep = ""),
        data = as.matrix(dat_CV_train))
        prediction[[i]] = predict(LDA_model[[i]], dat_CV_test)$class
      }
      
    }
    
    if (classifier == "QDA")
    {
      QDA_model <- list()
      prediction <- list()
      for (i in 1:K) {
        dat_CV_train = dat %>% filter(fold_index != i)
        dat_CV_test = dat %>% filter(fold_index == i)
        QDA_model[[i]] = qda(paste("train_label ~ ", paste(names(
          train_feature
        ), collapse = "+"), sep = ""),
        data = as.matrix(dat_CV_train))
        prediction[[i]] = predict(QDA_model[[i]], dat_CV_test)$class
      }
    }
    
    if (classifier == "NB")
    {
      NB_model <- list()
      prediction <- list()
      for (i in 1:K) {
        dat_CV_train = dat %>% filter(fold_index != i)
        dat_CV_test = dat %>% filter(fold_index == i)
        NB_model[[i]] = naiveBayes(dat_CV_train %>% dplyr::select(-train_label, -fold_index), 
                                   dat_CV_train$train_label)
        prediction[[i]] = predict(NB_model[[i]], dat_CV_test)
      }
    }
    
    
    
    if (loss_fun == "Accuracy")
    {
      Accuracy <- matrix(NA, ncol = K + 1, nrow = 1)
      for (j in 1:K)
      {
        dat_CV_test = dat %>% filter(fold_index == j)
        Accuracy[1, j] = mean(prediction[[j]] == dat_CV_test$train_label)
      }
      Accuracy[1, K + 1] = mean(Accuracy[1, 1:K])
      
    }
    
    return(Accuracy)
  }
```

# Remeber to transform variables! log

```{r}
set.seed(666)
CV_Master(
  classifier = "Logistic",
  train_coord = Image_Train_Cut[, 1:2],
  train_feature = Image_Train_Cut[, 4:11],
  train_label = Image_Train_Cut[, 3],
  K = 3,
  loss_fun = "Accuracy"
)

CV_Master(
  classifier = "LDA",
  train_coord = Image_Train_Cut[, 1:2],
  train_feature = Image_Train_Cut[, 4:11],
  train_label = Image_Train_Cut[, 3],
  K = 3,
  loss_fun = "Accuracy"
)

CV_Master(
  classifier = "QDA",
  train_coord = Image_Train_Cut[, 1:2],
  train_feature = Image_Train_Cut[, 4:11],
  train_label = Image_Train_Cut[, 3],
  K = 3,
  loss_fun = "Accuracy"
)

CV_Master(
  classifier = "NB",
  train_coord = Image_Train_Cut[, 1:2],
  train_feature = Image_Train_Cut[, 4:11],
  train_label = Image_Train_Cut[, 3],
  K =3,
  loss_fun = "Accuracy"
)

```


```{r}

```


# Model thoughts

```{r logistic}

train_feature <- Image_Train_Cut[, 4:6]
train_label <- Image_Train_Cut[, 3]

fold_index = kmeans(train_feature, centers = 5, nstart = 25)
dat = cbind(train_feature, train_label)
dat$fold_index = fold_index$cluster

dat_CV_train = dat %>% filter(fold_index != 1)
dat_CV_test = dat %>% filter(fold_index == 1)

M1.glm <- glm(paste("train_label ~ ", paste(names(train_feature), collapse = "+" ), sep = "" ), data = dat_CV_train, family = 'binomial')

prob <- predict(M1.glm, dat_CV_test , type="response")

prediction <- ifelse(prob > 0.5, 1, 0)
mean(prediction != dat_CV_test$train_label)
```


```{r LDA}
LDA_model <-
  lda(Cloud ~ NDAI + SD + CORR,
    data = Image_1_train
  )
mean(predict(LDA_model, Image_1_test)$class != Image_1_test$Cloud)

# klaR::partimat(Cloud ~ NDAI + SD + CORR, data = Image_1_train, method = "lda")
```


```{r QDA}
QDA_model <-
  lda(Cloud ~ NDAI + SD + CORR,
    data = Image_1_train
  )
mean(predict(QDA_model, Image_1_test)$class != Image_1_test$Cloud)
```


```{r NB}
naive_bayes <- naiveBayes(Cloud ~ NDAI + SD + CORR, 
                data=Image_1_train)
mean(predict(naive_bayes, Image_1_test) != Image_1_test$Cloud)
```



```{r PCA visual}
trn_pca <- Image_1_train %>% 
  filter(Cloud != "0") %>% 
  dplyr::select(-Cloud)  %>% 
  FactoMineR::PCA(graph = F)

proj <- trn_pca$ind$coord[, 1:2]  %>% 
  data.frame()  %>% 
  tibble()  %>% 
  mutate(Cloud_True = (Image_1_train %>% 
  filter(Cloud != "0") )$Cloud)

p1 <- proj %>% 
  ggplot(aes(x = Dim.1, y = Dim.2)) +
  geom_point(aes(color = Cloud_True)) +
  labs(x = "PC1", y = "PC2", title = "PCA Projections") 

p2 <- plot(trn_pca, choix = "var")

p1
```


## Testing


